### ISSUE TITLE
Usage with Goreleaser ?

### ISSUE THREAD

**Issue by sundowndev** [gobuffalo/packr#264]
Hi, thank you for developing this tool. I'd like to use it with Goreleaser but the "before" hook doesn't appear to make me allow to download and use packr. Do you have a solution for this ?

**Comment by jimschubert** [comment]
You can download packr before invoking goreleaser.

A [snippet from a GitHub Workflow](https://github.com/jimschubert/ossify/blob/master/.github/workflows/release.yml#L37-L47)

```
      - name: Get packr
        run: go get -u github.com/gobuffalo/packr/packr
      - name: Prepare
        run: git reset --hard
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Then, in your before hook:

```
before:
  hooks:
    - go mod tidy
    - packr
```
